import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Navbar from '@/components/Navbar'
import { Main } from '@/components/Main'
import Skills from '@/components/Skills'
import Bio from '@/components/Bio'
import Footer from '@/components/Footer'
import Projects from '@/components/Projects'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Hector</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="block">
                <div className="fixed z-50">
                    <Navbar />
                </div>
                <Main />
                <Skills />
                <Bio />
                <Projects />
                <Footer />
            </div>
        </>
    )
}
